# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66b1a7219114579c9df69fa0eac6ae44b6887ebdae70b9e660d5f2738cab6deb0c4de87f10ffbc31d4e3296775e5d64c511bf1ba5493adaf5490d7886d10a96

test:
  secret_key_base: 67e786027b6102ab55593206510e96c43038819d7d6a7bd005a6ef6415df2351d5402d9397d88678826bbbf75258af41a53b42de956b0aaa41dd08760b590555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
